"""
Database Update Script - Enrich Matched Contracts with CSV Metadata

Updates the 9 matched contracts found by compare_csv_portfolio.py with enriching
metadata from the CSV master table.

Updates include:
- external_data fields: region, filename, category, parking, facilities
- property gnr/bnr (cadastral numbers)
- contract status (only if CSV is more recent/accurate)

Usage:
    python3 scripts/update_from_csv.py [--dry-run]
"""

import sys
import os
import json
import asyncio
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from app.db.session import SessionLocal
from app.db import base  # Import all models
from app.domains.core.models.contract import Contract
from app.domains.core.models.property import Property
from app.domains.core.models.unit import Unit
from sqlalchemy import select

# ============================================================================
# UPDATE FUNCTIONS
# ============================================================================

async def load_comparison_report() -> Dict[str, Any]:
    """Load the comparison report generated by compare_csv_portfolio.py"""
    report_path = Path(__file__).parent.parent / 'data' / 'csv_comparison_report.json'
    
    if not report_path.exists():
        raise FileNotFoundError(
            f"Comparison report not found at {report_path}. "
            "Please run compare_csv_portfolio.py first."
        )
    
    with open(report_path, 'r', encoding='utf-8') as f:
        return json.load(f)


async def load_csv_data() -> Dict[str, Dict[str, Any]]:
    """Load CSV data indexed by row ID"""
    # Load parsed CSV data
    import csv
    csv_path = Path(__file__).parent.parent / 'data' / 'csv_portfolio_data.csv'
    
    # Import parsing functions from comparison script
    from compare_csv_portfolio import extract_contract_metadata
    
    csv_records = {}
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter=';')
        for row in reader:
            metadata = extract_contract_metadata(row)
            csv_records[metadata['csv_row_id']] = metadata
    
    return csv_records


async def update_contract_metadata(
    contract: Contract,
    csv_data: Dict[str, Any],
    session: Any
) -> List[str]:
    """
    Update contract external_data with CSV metadata.
    Returns list of changes made.
    """
    changes = []
    external_data = contract.external_data or {}
    
    # Fields to update in external_data
    metadata_fields = {
        'region': csv_data.get('region'),
        'filename': csv_data.get('filename'),
        'category': csv_data.get('category'),
        'parking': csv_data.get('parking'),
        'facilities': csv_data.get('facilities'),
        'termination_clause': csv_data.get('termination_clause'),
        'option_extension': csv_data.get('option_extension'),
        'duration': csv_data.get('duration')
    }
    
    for field, csv_value in metadata_fields.items():
        if csv_value:  # Only update if CSV has a value
            old_value = external_data.get(field)
            if old_value != csv_value:
                external_data[field] = csv_value
                changes.append(f"external_data.{field}: '{old_value}' → '{csv_value}'")
    
    if changes:
        contract.external_data = external_data
        # Mark as modified explicitly
        from sqlalchemy.orm import attributes
        attributes.flag_modified(contract, "external_data")
        session.add(contract)
    
    return changes


async def update_property_cadastral(
    property_obj: Property,
    csv_data: Dict[str, Any],
    session: Any
) -> List[str]:
    """
    Update property gnr/bnr if missing in database.
    Returns list of changes made.
    """
    changes = []
    
    # Update gnr if CSV has it and DB doesn't
    if csv_data.get('gnr') and not property_obj.gnr:
        property_obj.gnr = csv_data['gnr']
        changes.append(f"property.gnr: None → {csv_data['gnr']}")
        session.add(property_obj)
    
    # Update bnr if CSV has it and DB doesn't
    if csv_data.get('bnr') and not property_obj.bnr:
        property_obj.bnr = csv_data['bnr']
        changes.append(f"property.bnr: None → {csv_data['bnr']}")
        session.add(property_obj)
    
    return changes


async def perform_updates(dry_run: bool = False) -> Dict[str, Any]:
    """
    Perform database updates for matched records.
    
    Args:
        dry_run: If True, show changes but don't commit to database
        
    Returns:
        Dictionary with update statistics
    """
    print("=" * 80)
    print("DATABASE UPDATE - ENRICH WITH CSV METADATA")
    print("=" * 80)
    
    # Load data
    print("\n1. Loading comparison report and CSV data...")
    report = await load_comparison_report()
    csv_records = await load_csv_data()
    
    matched_records = [m for m in report['matches'] if m['has_differences']]
    print(f"   Found {len(matched_records)} matched records with differences to update")
    
    if not matched_records:
        print("\n✓ No records need updating. Database is already in sync!")
        return {'updated': 0, 'skipped': 0, 'errors': 0}
    
    # Prepare update log
    update_log = {
        'timestamp': datetime.now().isoformat(),
        'dry_run': dry_run,
        'records_processed': len(matched_records),
        'updates': []
    }
    
    stats = {'updated': 0, 'skipped': 0, 'errors': 0}
    
    # Process updates
    print(f"\n2. Processing updates...")
    print(f"   Mode: {'DRY RUN (no changes will be saved)' if dry_run else 'LIVE UPDATE'}")
    print()
    
    for i, match in enumerate(matched_records, 1):
        contract_id = match['contract_id']
        csv_row_id = match['csv_row_id']
        address = match['address']
        
        print(f"[{i}/{len(matched_records)}] {address} (Contract: {contract_id[:8]}...)")
        
        # Use separate session for each contract to avoid batch validation issues
        async with SessionLocal() as session:
            try:
                # Fetch contract with relationships
                stmt = select(Contract).where(Contract.contract_id == contract_id)
                result = await session.execute(stmt)
                contract = result.scalar_one_or_none()
                
                if not contract:
                    print(f"   ⚠️  Contract not found, skipping")
                    stats['skipped'] += 1
                    continue
                
                csv_data = csv_records.get(csv_row_id)
                if not csv_data:
                    print(f"   ⚠️  CSV data not found for row {csv_row_id}, skipping")
                    stats['skipped'] += 1
                    continue
                
                all_changes = []
                
                # Update contract metadata
                contract_changes = await update_contract_metadata(contract, csv_data, session)
                all_changes.extend(contract_changes)
                
                # Update property cadastral numbers if unit/property exists
                if contract.unit_id:
                    unit_stmt = select(Unit).where(Unit.unit_id == contract.unit_id)
                    unit_result = await session.execute(unit_stmt)
                    unit = unit_result.scalar_one_or_none()
                    
                    if unit and unit.property_id:
                        prop_stmt = select(Property).where(Property.property_id == unit.property_id)
                        prop_result = await session.execute(prop_stmt)
                        property_obj = prop_result.scalar_one_or_none()
                        
                        if property_obj:
                            prop_changes = await update_property_cadastral(property_obj, csv_data, session)
                            all_changes.extend(prop_changes)
                
                if all_changes:
                    for change in all_changes:
                        print(f"   ✓ {change}")
                    
                    # Commit this contract's changes immediately
                    if not dry_run:
                        await session.commit()
                    else:
                        await session.rollback()
                    
                    stats['updated'] += 1
                    update_log['updates'].append({
                        'contract_id': contract_id,
                        'csv_row_id': csv_row_id,
                        'address': address,
                        'changes': all_changes
                    })
                else:
                    print(f"   → No changes needed")
                    stats['skipped'] += 1
                
            except Exception as e:
                print(f"   ❌ Error: {e}")
                stats['errors'] += 1
                update_log['updates'].append({
                    'contract_id': contract_id,
                    'csv_row_id': csv_row_id,
                    'address': address,
                    'error': str(e)
                })
                await session.rollback()
            
            print()
    
    # Save update log
    log_path = Path(__file__).parent.parent / 'data' / 'update_log.json'
    with open(log_path, 'w', encoding='utf-8') as f:
        json.dump(update_log, f, indent=2, ensure_ascii=False)
    print(f"📝 Update log saved to {log_path}")
    
    return stats


# ============================================================================
# MAIN
# ============================================================================

async def main():
    """Main execution function."""
    dry_run = '--dry-run' in sys.argv
    
    try:
        stats = await perform_updates(dry_run=dry_run)
        
        print("\n" + "=" * 80)
        print("UPDATE SUMMARY")
        print("=" * 80)
        print(f"Updated:  {stats['updated']}")
        print(f"Skipped:  {stats['skipped']}")
        print(f"Errors:   {stats['errors']}")
        print("=" * 80)
        
        if dry_run and stats['updated'] > 0:
            print("\n💡 To apply these changes, run without --dry-run flag:")
            print("   python3 scripts/update_from_csv.py")
        elif stats['updated'] > 0:
            print("\n✅ Database successfully enriched with CSV metadata!")
        
    except FileNotFoundError as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    asyncio.run(main())
