"""
Database Update Script (Raw SQL) - Enrich Matched Contracts with CSV Metadata

Uses raw SQL to bypass ORM validation issues with contract status enum.
Directly updates external_data JSONB fields and property cadastral numbers.

Usage:
    python3 scripts/update_from_csv_sql.py [--dry-run]
"""

import sys
import os
import json
import asyncio
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from app.db.session import SessionLocal
from sqlalchemy import text

# ============================================================================
# DATA LOADING
# ============================================================================

async def load_comparison_report() -> Dict[str, Any]:
    """Load the comparison report generated by compare_csv_portfolio.py"""
    report_path = Path(__file__).parent.parent / 'data' / 'csv_comparison_report.json'
    
    if not report_path.exists():
        raise FileNotFoundError(
            f"Comparison report not found at {report_path}. "
            "Please run compare_csv_portfolio.py first."
        )
    
    with open(report_path, 'r', encoding='utf-8') as f:
        return json.load(f)


async def load_csv_data() -> Dict[str, Dict[str, Any]]:
    """Load CSV data indexed by row ID"""
    import csv
    from compare_csv_portfolio import extract_contract_metadata
    
    csv_path = Path(__file__).parent.parent / 'data' / 'csv_portfolio_data.csv'
    
    csv_records = {}
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter=';')
        for row in reader:
            metadata = extract_contract_metadata(row)
            csv_records[metadata['csv_row_id']] = metadata
    
    return csv_records


# ============================================================================
# RAW SQL UPDATE FUNCTIONS
# ============================================================================

async def update_contract_metadata_sql(
    session: Any,
    contract_id: str,
    csv_data: Dict[str, Any],
    dry_run: bool = False
) -> List[str]:
    """
    Update contract external_data using raw SQL JSONB operations.
    Returns list of changes made.
    """
    changes = []
    
    # Build JSONB update operations
    metadata_fields = {
        'region': csv_data.get('region'),
        'filename': csv_data.get('filename'),
        'category': csv_data.get('category'),
        'parking': csv_data.get('parking'),
        'facilities': csv_data.get('facilities'),
        'termination_clause': csv_data.get('termination_clause'),
        'option_extension': csv_data.get('option_extension'),
        'duration': csv_data.get('duration')
    }
    
    # Filter out None values
    updates = {k: v for k, v in metadata_fields.items() if v}
    
    if not updates:
        return []
    
    # Get current external_data
    result = await session.execute(
        text("SELECT external_data FROM contracts WHERE contract_id = :contract_id"),
        {"contract_id": contract_id}
    )
    row = result.fetchone()
    
    if not row:
        return []
    
    current_data = row[0] or {}
    
    # Check what has changed
    for field, new_value in updates.items():
        old_value = current_data.get(field)
        if old_value != new_value:
            changes.append(f"external_data.{field}: '{old_value}' → '{new_value}'")
    
    if not changes:
        return []
    
    # Merge updates into external_data
    merged_data = {**(current_data or {}), **updates}
    
    # Update using raw SQL
    if not dry_run:
        await session.execute(
            text("""
                UPDATE contracts 
                SET external_data = CAST(:new_data AS jsonb),
                    updated_at = now()
                WHERE contract_id = CAST(:contract_id AS uuid)
            """),
            {
                "contract_id": str(contract_id),
                "new_data": json.dumps(merged_data)
            }
        )
    
    return changes


async def update_property_cadastral_sql(
    session: Any,
    property_id: str,
    csv_data: Dict[str, Any],
    dry_run: bool = False
) -> List[str]:
    """
    Update property gnr/bnr using raw SQL.
    Returns list of changes made.
    """
    changes = []
    
    # Get current property data
    result = await session.execute(
        text("SELECT gnr, bnr FROM properties WHERE property_id = :property_id"),
        {"property_id": property_id}
    )
    row = result.fetchone()
    
    if not row:
        return []
    
    current_gnr, current_bnr = row
    csv_gnr = csv_data.get('gnr')
    csv_bnr = csv_data.get('bnr')
    
    # Update gnr if CSV has it and DB doesn't
    if csv_gnr and not current_gnr:
        changes.append(f"property.gnr: None → {csv_gnr}")
        if not dry_run:
            await session.execute(
                text("UPDATE properties SET gnr = :gnr, updated_at = now() WHERE property_id = :property_id"),
                {"gnr": csv_gnr, "property_id": property_id}
            )
    
    # Update bnr if CSV has it and DB doesn't
    if csv_bnr and not current_bnr:
        changes.append(f"property.bnr: None → {csv_bnr}")
        if not dry_run:
            await session.execute(
                text("UPDATE properties SET bnr = :bnr, updated_at = now() WHERE property_id = :property_id"),
                {"bnr": csv_bnr, "property_id": property_id}
            )
    
    return changes


# ============================================================================
# MAIN UPDATE FUNCTION
# ============================================================================

async def perform_updates(dry_run: bool = False) -> Dict[str, Any]:
    """
    Perform database updates using raw SQL.
    
    Args:
        dry_run: If True, show changes but don't commit to database
        
    Returns:
        Dictionary with update statistics
    """
    print("=" * 80)
    print("DATABASE UPDATE - ENRICH WITH CSV METADATA (Raw SQL)")
    print("=" * 80)
    
    # Load data
    print("\n1. Loading comparison report and CSV data...")
    report = await load_comparison_report()
    csv_records = await load_csv_data()
    
    matched_records = [m for m in report['matches'] if m['has_differences']]
    print(f"   Found {len(matched_records)} matched records with differences to update")
    
    if not matched_records:
        print("\n✓ No records need updating. Database is already in sync!")
        return {'updated': 0, 'skipped': 0, 'errors': 0}
    
    # Prepare update log
    update_log = {
        'timestamp': datetime.now().isoformat(),
        'dry_run': dry_run,
        'records_processed': len(matched_records),
        'updates': []
    }
    
    stats = {'updated': 0, 'skipped': 0, 'errors': 0}
    
    # Process updates
    print(f"\n2. Processing updates...")
    print(f"   Mode: {'DRY RUN (no changes will be saved)' if dry_run else 'LIVE UPDATE'}")
    print()
    
    for i, match in enumerate(matched_records, 1):
        contract_id = match['contract_id']
        csv_row_id = match['csv_row_id']
        address = match['address']
        
        print(f"[{i}/{len(matched_records)}] {address} (Contract: {contract_id[:8]}...)")
        
        # Use separate session for each contract
        async with SessionLocal() as session:
            try:
                csv_data = csv_records.get(csv_row_id)
                if not csv_data:
                    print(f"   ⚠️  CSV data not found for row {csv_row_id}, skipping")
                    stats['skipped'] += 1
                    continue
                
                all_changes = []
                
                # Update contract metadata
                contract_changes = await update_contract_metadata_sql(
                    session, contract_id, csv_data, dry_run
                )
                all_changes.extend(contract_changes)
                
                # Get property_id via unit
                result = await session.execute(
                    text("""
                        SELECT u.property_id 
                        FROM contracts c
                        JOIN units u ON c.unit_id = u.unit_id
                        WHERE c.contract_id = :contract_id
                    """),
                    {"contract_id": contract_id}
                )
                row = result.fetchone()
                
                if row and row[0]:
                    property_id = row[0]
                    prop_changes = await update_property_cadastral_sql(
                        session, property_id, csv_data, dry_run
                    )
                    all_changes.extend(prop_changes)
                
                if all_changes:
                    for change in all_changes:
                        print(f"   ✓ {change}")
                    
                    # Commit this contract's changes
                    if not dry_run:
                        await session.commit()
                    else:
                        await session.rollback()
                    
                    stats['updated'] += 1
                    update_log['updates'].append({
                        'contract_id': contract_id,
                        'csv_row_id': csv_row_id,
                        'address': address,
                        'changes': all_changes
                    })
                else:
                    print(f"   → No changes needed")
                    stats['skipped'] += 1
                
            except Exception as e:
                print(f"   ❌ Error: {e}")
                stats['errors'] += 1
                update_log['updates'].append({
                    'contract_id': contract_id,
                    'csv_row_id': csv_row_id,
                    'address': address,
                    'error': str(e)
                })
                await session.rollback()
            
            print()
    
    # Save update log
    log_path = Path(__file__).parent.parent / 'data' / 'update_log_sql.json'
    with open(log_path, 'w', encoding='utf-8') as f:
        json.dump(update_log, f, indent=2, ensure_ascii=False)
    print(f"📝 Update log saved to {log_path}")
    
    return stats


# ============================================================================
# MAIN
# ============================================================================

async def main():
    """Main execution function."""
    dry_run = '--dry-run' in sys.argv
    
    try:
        stats = await perform_updates(dry_run=dry_run)
        
        print("\n" + "=" * 80)
        print("UPDATE SUMMARY")
        print("=" * 80)
        print(f"Updated:  {stats['updated']}")
        print(f"Skipped:  {stats['skipped']}")
        print(f"Errors:   {stats['errors']}")
        print("=" * 80)
        
        if dry_run and stats['updated'] > 0:
            print("\n💡 To apply these changes, run without --dry-run flag:")
            print("   python3 scripts/update_from_csv_sql.py")
        elif stats['updated'] > 0:
            print("\n✅ Database successfully enriched with CSV metadata!")
        
    except FileNotFoundError as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    asyncio.run(main())
