"""postgis_and_ns3451

Revision ID: 6b2bea70fd4d
Revises: 17eae0f4d1d3
Create Date: 2026-02-10 20:26:30.150243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b2bea70fd4d'
down_revision: Union[str, Sequence[str], None] = '17eae0f4d1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Enable PostGIS Extension — only if available on this host
    conn = op.get_bind()
    postgis_avail = conn.execute(sa.text(
        "SELECT 1 FROM pg_available_extensions WHERE name = 'postgis'"
    )).fetchone()
    if postgis_avail:
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    else:
        print("WARNING: PostGIS extension not available on this host, skipping.")

    # 2. Create NS 3451 Table (conditionally)
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                    AND table_name = 'ns3451_codes'
            ) THEN
                CREATE TABLE public.ns3451_codes (
                    code varchar(20) NOT NULL,
                    name varchar(255) NOT NULL,
                    level integer NOT NULL,
                    parent_code varchar(20),
                    CONSTRAINT ns3451_codes_pkey PRIMARY KEY (code),
                    CONSTRAINT ns3451_codes_parent_code_fkey FOREIGN KEY (parent_code) REFERENCES public.ns3451_codes(code)
                );
            END IF;
        END
        $$;
        """
    )
    # Create index only if table exists
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'ns3451_codes'
            ) THEN
                CREATE INDEX IF NOT EXISTS ix_ns3451_codes_code ON public.ns3451_codes (code);
            END IF;
        END $$;
    """)

    # 3. Add NS 3451 Code to Building Components (conditionally)
    # Only add column and FK if building_components table exists
    op.execute("""
        DO $$
        BEGIN
            -- Only proceed if building_components table exists
            IF EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'building_components'
            ) THEN
                -- Add column if it doesn't exist
                ALTER TABLE public.building_components ADD COLUMN IF NOT EXISTS ns3451_code varchar(20);

                -- Add FK constraint if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints tc
                    WHERE tc.table_schema = 'public'
                        AND tc.table_name = 'building_components'
                        AND tc.constraint_name = 'building_components_ns3451_code_fkey'
                ) THEN
                    ALTER TABLE public.building_components
                        ADD CONSTRAINT building_components_ns3451_code_fkey
                        FOREIGN KEY (ns3451_code) REFERENCES public.ns3451_codes(code);
                END IF;
            END IF;
        END $$;
    """)

    # 4 & 5. Add Geometry to Properties — only if PostGIS is available
    if postgis_avail:
        op.execute("ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS geom geometry(POINT, 4326)")

        op.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public'
                        AND table_name = 'properties'
                        AND column_name = 'geom'
                ) THEN
                    CREATE INDEX IF NOT EXISTS idx_properties_geom ON public.properties USING gist (geom);
                END IF;
            END $$;
        """)

        op.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public'
                        AND table_name = 'properties'
                        AND column_name = 'geom'
                        AND udt_name = 'geometry'
                ) THEN
                    UPDATE properties
                    SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
                    WHERE latitude IS NOT NULL
                        AND longitude IS NOT NULL
                        AND geom IS NULL;
                END IF;
            END $$;
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mfa_verified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_units_property_id'), 'units', ['property_id'], unique=False)
    op.create_index(op.f('idx_units_property_id'), 'units', ['property_id'], unique=False)
    op.add_column('text_content', sa.Column('source_index_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('text_content_source_index_id_key'), 'text_content', ['source_index_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_text_content_unit_id'), 'text_content', ['unit_id'], unique=False)
    op.create_index(op.f('ix_text_content_source_type'), 'text_content', ['source_type'], unique=False)
    op.create_index(op.f('ix_text_content_property_id'), 'text_content', ['property_id'], unique=False)
    op.create_index(op.f('ix_text_content_created_at'), 'text_content', ['created_at'], unique=False)
    op.create_index(op.f('ix_text_content_contract_id'), 'text_content', ['contract_id'], unique=False)
    op.create_index(op.f('idx_text_content_source_index_id'), 'text_content', ['source_index_id'], unique=False)
    op.create_index(op.f('ix_risk_factors_factor_name'), 'risk_factors', ['factor_name'], unique=False)
    op.create_index(op.f('ix_risk_factors_category'), 'risk_factors', ['category'], unique=False)
    op.create_index(op.f('ix_risk_assessments_property_date'), 'risk_assessments', ['property_id', sa.literal_column('assessment_date DESC')], unique=False)
    op.create_index(op.f('ix_risk_assessments_assessment_date'), 'risk_assessments', ['assessment_date'], unique=False)
    op.create_index(op.f('ix_proximity_services_service_type'), 'proximity_services', ['service_type'], unique=False)
    op.create_index(op.f('ix_proximity_services_property_id'), 'proximity_services', ['property_id'], unique=False)
    op.create_index(op.f('ix_proximity_services_property_expires'), 'proximity_services', ['property_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_proximity_services_expires_at'), 'proximity_services', ['expires_at'], unique=False)
    op.create_index(op.f('ix_proximity_services_distance'), 'proximity_services', ['distance_meters'], unique=False)
    op.drop_index(op.f('ix_properties_postal_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_address'), table_name='properties')
    op.drop_index('idx_properties_geom', table_name='properties', postgresql_using='gist')
    op.create_index(op.f('idx_properties_region'), 'properties', ['region'], unique=False)
    op.create_index(op.f('idx_properties_name'), 'properties', ['name'], unique=False)
    op.create_index(op.f('idx_properties_fulltext'), 'properties', [sa.literal_column("to_tsvector('norwegian'::regconfig, (((((name::text || ' '::text) || address::text) || ' '::text) || city::text) || ' '::text) || region::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('idx_properties_address'), 'properties', ['address'], unique=False)
    op.drop_column('properties', 'geom')
    op.create_index(op.f('ix_parties_orgnr'), 'parties', ['orgnr'], unique=True)
    op.create_index(op.f('idx_parties_orgnr'), 'parties', ['orgnr'], unique=False)
    op.create_index(op.f('idx_parties_name'), 'parties', ['name'], unique=False)
    op.create_index(op.f('ix_natural_hazard_events_type'), 'natural_hazard_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_natural_hazard_events_severity'), 'natural_hazard_events', ['severity'], unique=False)
    op.create_index(op.f('ix_natural_hazard_events_location'), 'natural_hazard_events', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_natural_hazard_events_date'), 'natural_hazard_events', ['event_date'], unique=False)
    op.create_index(op.f('idx_gl_year_month_amount'), 'gl_transactions', ['year', 'month', 'amount'], unique=False)
    op.create_index(op.f('idx_gl_property_year_month'), 'gl_transactions', ['property_id', 'year', 'month'], unique=False)
    op.create_index(op.f('ix_geological_data_property_id'), 'geological_data', ['property_id'], unique=False)
    op.create_index(op.f('ix_geological_data_landslide_risk'), 'geological_data', ['landslide_risk'], unique=False)
    op.create_index(op.f('ix_file_meta_sha256'), 'file_meta', ['sha256'], unique=True)
    op.create_index(op.f('ix_file_meta_contract_id'), 'file_meta', ['contract_id'], unique=False)
    op.create_index(op.f('ix_external_api_data_source'), 'external_api_data', ['source_api'], unique=False)
    op.create_index(op.f('ix_external_api_data_fetched_at'), 'external_api_data', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_external_api_data_entity'), 'external_api_data', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_environmental_data_property_id'), 'environmental_data', ['property_id'], unique=False)
    op.add_column('contracts', sa.Column('filename_region', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('elements', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('filename_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('filename_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_contracts_filename_unique'), 'contracts', ['filename_region', 'filename_type', 'filename_number'], unique=True, postgresql_where='((filename_region IS NOT NULL) AND (filename_type IS NOT NULL) AND (filename_number IS NOT NULL))')
    op.create_index(op.f('ix_contracts_elements'), 'contracts', ['elements'], unique=False)
    op.create_index(op.f('idx_contracts_end_date'), 'contracts', [sa.literal_column("(external_data ->> 'end_date'::text)")], unique=False)
    op.drop_constraint(None, 'checklist_templates', type_='foreignkey')
    op.drop_constraint(None, 'building_components', type_='foreignkey')
    op.drop_column('building_components', 'ns3451_code')
    op.add_column('ai_tools', sa.Column('vector_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('agent_memory_embedding_idx'), 'agent_memory', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'activity_templates', type_='foreignkey')
    op.create_table('socioeconomic_data',
    sa.Column('socio_data_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('municipality_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('crime_rate_per_1000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unemployment_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('median_income', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('population_density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('demographic_profile', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('socioeconomic_data_property_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('socio_data_id', name=op.f('socioeconomic_data_pkey'))
    )
    op.create_index(op.f('ix_socioeconomic_data_year'), 'socioeconomic_data', ['year'], unique=False)
    op.create_index(op.f('ix_socioeconomic_data_property_id'), 'socioeconomic_data', ['property_id'], unique=False)
    op.create_index(op.f('ix_socioeconomic_data_municipality'), 'socioeconomic_data', ['municipality_code'], unique=False)
    op.create_table('nextauth_accounts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('providerAccountId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_in', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ext_expires_in', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['nextauth_users.id'], name=op.f('nextauth_accounts_userid_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nextauth_accounts_pkey')),
    sa.UniqueConstraint('provider', 'providerAccountId', name=op.f('nextauth_accounts_provider_providerAccountId_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('batch_jobs',
    sa.Column('job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_items', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('processed_items', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('success_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failed_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('property_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'running'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])", name=op.f('check_batch_job_status')),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('check_batch_job_progress')),
    sa.PrimaryKeyConstraint('job_id', name=op.f('batch_jobs_pkey'))
    )
    op.create_index(op.f('ix_batch_jobs_worker_id'), 'batch_jobs', ['worker_id'], unique=False)
    op.create_index(op.f('ix_batch_jobs_status'), 'batch_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_batch_jobs_job_type'), 'batch_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_batch_jobs_created_at'), 'batch_jobs', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('actor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('log_id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('api_usage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('request_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('api_usage_pkey'))
    )
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_usage_model'), 'api_usage', ['model'], unique=False)
    op.create_index(op.f('ix_api_usage_endpoint'), 'api_usage', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_usage_created_at'), 'api_usage', ['created_at'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('orgnr', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('supplier_id', name='suppliers_pkey'),
    sa.UniqueConstraint('name', name='suppliers_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('orgnr', name='suppliers_orgnr_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='User-friendly scenario name'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Scenario description'),
    sa.Column('base_forecast_id', sa.UUID(), autoincrement=False, nullable=True, comment='Reference to baseline forecast'),
    sa.Column('modifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of changes applied to baseline'),
    sa.Column('result_forecast', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Resulting forecast after modifications'),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='User ID or email'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['base_forecast_id'], ['forecast_cache.forecast_id'], name=op.f('scenarios_base_forecast_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('scenario_id', name=op.f('scenarios_pkey'))
    )
    op.create_index(op.f('idx_scenarios_created_by'), 'scenarios', ['created_by'], unique=False)
    op.create_index(op.f('idx_scenarios_created_at'), 'scenarios', ['created_at'], unique=False)
    op.create_index(op.f('idx_scenarios_base_forecast'), 'scenarios', ['base_forecast_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_sql', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('query_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('execution_success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('result_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cache_hit', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('parent_log_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_log_id'], ['query_logs.log_id'], name=op.f('fk_query_logs_parent'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('query_logs_pkey'))
    )
    op.create_index(op.f('idx_query_logs_timestamp'), 'query_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_query_logs_success'), 'query_logs', ['execution_success'], unique=False)
    op.create_index(op.f('idx_query_logs_query_type'), 'query_logs', ['query_type'], unique=False)
    op.create_index(op.f('idx_query_logs_model'), 'query_logs', ['model_used'], unique=False)
    op.create_index(op.f('idx_query_logs_confidence'), 'query_logs', ['confidence_score'], unique=False)
    op.create_table('graph_relationships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['graph_entities.id'], name=op.f('graph_relationships_source_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['graph_entities.id'], name=op.f('graph_relationships_target_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_relationships_pkey'))
    )
    op.create_index(op.f('ix_graph_relationships_type'), 'graph_relationships', ['relation_type'], unique=False)
    op.create_index(op.f('ix_graph_relationships_target'), 'graph_relationships', ['target_id'], unique=False)
    op.create_index(op.f('ix_graph_relationships_source'), 'graph_relationships', ['source_id'], unique=False)
    op.create_table('nextauth_verification_tokens',
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.UniqueConstraint('identifier', 'token', name=op.f('nextauth_verification_tokens_identifier_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('token', name=op.f('nextauth_verification_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('infrastructure_costs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('collection_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('raw_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('estimated_cost_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('active_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpu_used_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('storage_gb', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('bandwidth_gb', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('infrastructure_costs_pkey'))
    )
    op.create_index(op.f('idx_costs_service_date'), 'infrastructure_costs', ['service_name', 'collection_date'], unique=False)
    op.create_index(op.f('idx_costs_collection_date'), 'infrastructure_costs', ['collection_date'], unique=False)
    op.create_table('dashboard_metrics',
    sa.Column('metric_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('properties_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contracts_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('risks_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_annual_rent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_maintenance_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('critical_deviations', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('expiring_contracts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('overdue_tasks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('metric_id', name=op.f('dashboard_metrics_pkey'))
    )
    op.create_index(op.f('ix_dashboard_metrics_metric_id'), 'dashboard_metrics', ['metric_id'], unique=False)
    op.create_table('query_library',
    sa.Column('query_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('query_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Descriptive name generated from SQL pattern'),
    sa.Column('user_question_pattern', sa.TEXT(), autoincrement=False, nullable=False, comment='Example user question that this query answers'),
    sa.Column('sql_template', sa.TEXT(), autoincrement=False, nullable=False, comment='The SQL query template'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Auto-generated description of what this query does'),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of times this query has been used'),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Success rate (0.0-1.0) of query executions'),
    sa.Column('avg_execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True, comment='Average execution time in milliseconds'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='auto (system-generated) or manual (human-created)'),
    sa.PrimaryKeyConstraint('query_id', name=op.f('query_library_pkey')),
    sa.UniqueConstraint('query_name', name=op.f('query_library_query_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_query_library_usage'), 'query_library', ['usage_count'], unique=False)
    op.create_index(op.f('idx_query_library_success'), 'query_library', ['success_rate'], unique=False)
    op.create_index(op.f('idx_query_library_question_search'), 'query_library', [sa.literal_column("to_tsvector('norwegian'::regconfig, user_question_pattern)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_query_library_created'), 'query_library', ['created_at'], unique=False)
    op.create_table('graph_entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_entities_pkey'))
    )
    op.create_index(op.f('ix_graph_entities_name'), 'graph_entities', ['name'], unique=False)
    op.create_index(op.f('ix_graph_entities_label'), 'graph_entities', ['label'], unique=False)
    op.create_table('generated_tools',
    sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('python_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sql_pattern', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_log_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tool_id', name=op.f('generated_tools_pkey'))
    )
    op.create_index(op.f('ix_generated_tools_status'), 'generated_tools', ['status'], unique=False)
    op.create_index(op.f('ix_generated_tools_name'), 'generated_tools', ['name'], unique=True)
    op.create_table('nextauth_users',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emailVerified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nextauth_users_pkey'),
    sa.UniqueConstraint('email', name='nextauth_users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('session_id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('ix_sessions_user_email'), 'sessions', ['user_email'], unique=False)
    op.create_table('action_recommendations',
    sa.Column('recommendation_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('recommendation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type: kpi_adjustment, renegotiation, consolidation, etc'),
    sa.Column('target_entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Entity type: contract, property'),
    sa.Column('target_entity_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID of target contract/property'),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False, comment='Priority 1-5 (1=highest cost savings)'),
    sa.Column('estimated_impact_nok', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='Estimated annual cost savings in NOK'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False, comment='Human-readable action description'),
    sa.Column('ai_rationale', sa.TEXT(), autoincrement=False, nullable=True, comment='GPT-4 explanation of why this recommendation was made'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Status: pending, simulated, executed'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('recommendation_id', name=op.f('action_recommendations_pkey'))
    )
    op.create_index(op.f('idx_recommendations_status'), 'action_recommendations', ['status'], unique=False)
    op.create_index(op.f('idx_recommendations_priority'), 'action_recommendations', ['priority'], unique=False)
    op.create_index(op.f('idx_recommendations_impact'), 'action_recommendations', ['estimated_impact_nok'], unique=False)
    op.create_index(op.f('idx_recommendations_entity'), 'action_recommendations', ['target_entity_type', 'target_entity_id'], unique=False)
    op.create_index(op.f('idx_recommendations_created'), 'action_recommendations', ['created_at'], unique=False)
    op.create_table('forecast_cache',
    sa.Column('forecast_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=True, comment='Property ID (nullable for portfolio-wide forecasts)'),
    sa.Column('forecast_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type: cash_flow, cost_forecast, monte_carlo'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Forecast parameters (months_ahead, kpi_adjustment, etc)'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Full forecast data with P10/P50/P90'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Auto-delete after this timestamp (24h TTL)'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('forecast_cache_property_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id', name=op.f('forecast_cache_pkey'))
    )
    op.create_index(op.f('idx_forecast_type'), 'forecast_cache', ['forecast_type'], unique=False)
    op.create_index(op.f('idx_forecast_property'), 'forecast_cache', ['property_id'], unique=False)
    op.create_index(op.f('idx_forecast_expiry'), 'forecast_cache', ['expires_at'], unique=False)
    op.create_index(op.f('idx_forecast_created'), 'forecast_cache', ['created_at'], unique=False)
    op.create_table('nextauth_sessions',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sessionToken', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['nextauth_users.id'], name=op.f('nextauth_sessions_userid_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nextauth_sessions_pkey')),
    sa.UniqueConstraint('sessionToken', name=op.f('nextauth_sessions_sessionToken_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('pending_script_executions',
    sa.Column('execution_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('script_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('execution_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('execution_id', name=op.f('pending_script_executions_pkey'))
    )
    op.create_table('external_risk_errors',
    sa.Column('error_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('http_status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('resolved', sa.VARCHAR(length=10), server_default=sa.text("'false'::character varying"), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('external_risk_errors_property_id_fkey')),
    sa.PrimaryKeyConstraint('error_id', name=op.f('external_risk_errors_pkey'))
    )
    op.create_index(op.f('ix_external_risk_errors_source'), 'external_risk_errors', ['source'], unique=False)
    op.create_index(op.f('ix_external_risk_errors_resolved'), 'external_risk_errors', ['resolved'], unique=False)
    op.create_index(op.f('ix_external_risk_errors_property_id'), 'external_risk_errors', ['property_id'], unique=False)
    op.create_index(op.f('ix_external_risk_errors_error_type'), 'external_risk_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_external_risk_errors_created_at'), 'external_risk_errors', ['created_at'], unique=False)
    op.create_table('expenses',
    sa.Column('expense_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('expenses_property_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('expenses_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('expense_id', name=op.f('expenses_pkey'))
    )
    op.create_index(op.f('idx_expenses_year'), 'expenses', ['year'], unique=False)
    op.create_index(op.f('idx_expenses_supplier_id'), 'expenses', ['supplier_id'], unique=False)
    op.create_index(op.f('idx_expenses_property_id'), 'expenses', ['property_id'], unique=False)
    op.create_index(op.f('idx_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('idx_expenses_category'), 'expenses', ['category'], unique=False)
    op.drop_index(op.f('ix_ns3451_codes_code'), table_name='ns3451_codes')
    op.drop_table('ns3451_codes')
    # ### end Alembic commands ###
