"""
100 eksempelspørsmål for KI Kollega (enkel modus).
Brukes av GET /api/v1/ai/suggestions for å vise varierte forslag til brukeren.
"""

# Kategorier: eiendommer, kontrakter, kostnad, parter, enheter, sentre, tellinger, sammenligninger, oversikt
KI_KOLLEGA_EKSEMPELSPORSMAL = [
    # --- Eiendommer (areal, størrelse, region, adresse) ---
    "Hvilke eiendommer er størst i kvm?",
    "List opp eiendommer med mest areal",
    "Hvilke eiendommer har minst areal?",
    "Hvor mange eiendommer har vi?",
    "Hvilke eiendommer ligger i Oslo?",
    "List eiendommer per region",
    "Hvilke eiendommer tilhører region Øst?",
    "Finn eiendommer i Bergen",
    "Hva er adressen til eiendom X?",
    "Hvilke eiendommer har adresse i Storgata?",
    "Sorter eiendommer på areal synkende",
    "Gi meg de 10 største eiendommer",
    "Hvilken eiendom har størst totalt areal?",
    "List alle eiendommer med navn og adresse",
    "Hvilke eiendommer finnes i region 12?",
    "Finn eiendommer etter by",
    "Hvor mange kvm har vi totalt i porteføljen?",
    "Hvilke eiendommer har over 5000 kvm?",
    "List eiendommer under 1000 kvm",
    "Hva heter eiendommen på adresse X?",
    # --- Kostnad (per kvm, totalt, region) ---
    "Hvilke eiendommer har høyest kostnad per kvm?",
    "Hvilke eiendommer har lavest kostnad per kvm?",
    "Sorter eiendommer på kostnad per kvm",
    "Hva er totalkostnaden for vedlikehold per eiendom?",
    "Hvilke 5 eiendommer koster mest i vedlikehold?",
    "Hvilke eiendommer har lavest vedlikeholdskostnad?",
    "Gi meg kostnad per kvm for alle eiendommer",
    "Hvor mye bruker vi totalt på vedlikehold?",
    "Sammenlign kostnad per kvm på tvers av regioner",
    "Hvilken eiendom har høyest kostnad per kvadratmeter?",
    "List eiendommer etter totalkostnad synkende",
    "Hva er gjennomsnittlig kostnad per kvm?",
    "Hvilke eiendommer har kostnad over 1000 kr per kvm?",
    "Finn eiendommer med lavest kostnad per kvm",
    "Oppsummer vedlikeholdskostnader per region",
    # --- Kontrakter (utløp, part, status, kategori) ---
    "Hvilke kontrakter utløper snart?",
    "List kontrakter som utløper i 2025",
    "Hvilke kontrakter har utløpsdato før sommeren?",
    "Hvor mange aktive kontrakter har vi?",
    "Hvilke kontrakter er terminert?",
    "List alle kontrakter med utløpsdato og part",
    "Hvilken part har flest kontrakter?",
    "Hvilke kontrakter er knyttet til eiendom X?",
    "Når utløper kontrakten for part Y?",
    "Finn kontrakter med status aktiv",
    "Hvilke kontrakter er av typen Leiekontrakt?",
    "List Serviceavtaler",
    "Hvilke kontrakter utløper i løpet av 6 måneder?",
    "Sorter kontrakter på utløpsdato",
    "Hvor mange kontrakter utløper i 2026?",
    "Hvilke eiendommer har kontrakter som utløper snart?",
    "List kontrakter per part",
    "Hvilke parter har kontrakt på eiendom Z?",
    "Finn aktive kontrakter per eiendom",
    "Hva er utløpsdatoen for kontraktene til part A?",
    # --- Parter (leietakere, orgnr, kontakt) ---
    "Hvilke parter har vi i systemet?",
    "Finn part med orgnr 123456789",
    "List alle parter med navn og e-post",
    "Hvilke parter mangler kontakttelefon?",
    "Hvor mange parter er registrert?",
    "Finn parter med e-post som inneholder @example.com",
    "List parter alfabetisk",
    "Hvilke parter har kontrakt på eiendom X?",
    "Gi meg kontaktinfo for part Y",
    "Hvilke parter har orgnr registrert?",
    "List leietakere med telefonnummer",
    "Finn part etter navn",
    "Hvilke parter har flest kontrakter?",
    "Oppsummer parter per eiendom",
    "Hvor mange parter har vi uten e-post?",
    # --- Enheter (lokaler, formål, areal, etasje) ---
    "Hvilke enheter finnes på eiendom X?",
    "List enheter med formål kontor",
    "Hvor mange enheter har vi totalt?",
    "Hvilke enheter har størst areal?",
    "List enheter per etasje for eiendom Y",
    "Finn enheter med zone_type BEBO",
    "Hvilke enheter har areal over 500 kvm?",
    "List alle enheter med eiendomsnavn og formål",
    "Hva er totalt enhetsareal per eiendom?",
    "Hvilke enheter er UU-tilpasset?",
    "Sorter enheter på areal",
    "Finn enheter i etasje 2",
    "Hvilke eiendommer har flest enheter?",
    "List enheter med formål butikk",
    "Hvor mange kvm enheter har eiendom Z?",
    "Hvilke enheter har sone ANSA?",
    # --- Sentre (kriseentre, region) ---
    "Hvilke sentre finnes i systemet?",
    "List kriseentre per region",
    "Hva er beskrivelsen av senter X?",
    "Hvilke sentre ligger i region Øst?",
    "Hvor mange sentre har vi?",
    "Finn sentre med navn som inneholder Ungdom",
    "List alle sentre med region",
    "Hvilket senter har region Y?",
    # --- Tellinger og oversikt ---
    "Gi meg en oversikt over porteføljen",
    "Hvor mange eiendommer, kontrakter og parter har vi?",
    "Oppsummer antall eiendommer per region",
    "Hvor mange aktive kontrakter per eiendom?",
    "Gi meg nøkkeltall for hele porteføljen",
    "Hva er totalt antall enheter?",
    "List topp 10 eiendommer etter areal",
    "List topp 10 eiendommer etter kostnad per kvm",
    "Hvilke regioner har vi?",
    "Oppsummer: antall eiendommer, kontrakter, parter",
    # --- Sammenligninger og analyse ---
    "Sammenlign eiendom A og B på areal og kostnad",
    "Hvilke eiendommer har både høyt areal og lav kostnad per kvm?",
    "Sammenlign regionene på antall eiendommer",
    "Hvor stor andel av kontraktene utløper i 2025?",
    "Hvilken region har høyest totalt vedlikeholdskostnad?",
    "Sammenlign kostnad per kvm på de 5 største eiendommer",
    "Hvilke eiendommer har kontrakter som utløper og høyt areal?",
    "Gi meg en kort status på porteføljen",
    "Hva bør jeg følge opp nå?",
    "Hvilke eiendommer bør vi se nærmere på?",
]

# Gruppert etter entity_type for kontekstbaserte forslag
SUGGESTIONS_BY_ENTITY_TYPE = {
    "property": [
        "Hva er de viktigste kostnadene for denne eiendommen?",
        "Hvilke kontrakter er knyttet til denne eiendommen?",
        "Hva er kostnad per kvm for denne eiendommen?",
        "Hvilke enheter finnes på denne eiendommen?",
        "Sammenlign denne eiendommen med lignende eiendommer",
        "Er det kontrakter som utløper snart på denne eiendommen?",
        "Hvor stort er arealet på denne eiendommen?",
        "Hvilke parter har kontrakt på denne eiendommen?",
        "Vis vedlikeholdskostnader for denne eiendommen",
        "Hvilken region tilhører denne eiendommen?",
    ],
    "contract": [
        "Når utløper denne kontrakten?",
        "Hvem er leietaker/part i denne kontrakten?",
        "Hvilken eiendom er kontrakten knyttet til?",
        "Hva er kontraktens kategori og status?",
        "Sammenlign med andre kontrakter på samme eiendom",
        "Har denne kontrakten opsjon?",
        "Hva er kontraktens startdato?",
    ],
    "party": [
        "Hvilke kontrakter har denne parten?",
        "På hvilke eiendommer har denne parten kontrakt?",
        "Når utløper kontraktene til denne parten?",
        "Gi meg kontaktinfo for denne parten",
        "Hvor mange kontrakter har denne parten?",
    ],
}
